package com.example.micromatch.enums;

public enum TunisianReferee {
    ALI_BEN_NASSER,
    MOURAD_DAAMI,
    NEJI_JOUINI,
    HICHEM_GUIRAT,
    SLIM_JEDIDI,
    YOUSSEF_SRAIRI,
    SADOK_SELMI,
    HAYTHEM_GUIRAT,
    NIDHAL_BEN_LTAIEF,
    MOHAMED_YOUSRI_BOUALI,
    FADI_BOUKHRIS,
    WALID_HEDHLI,
    IHEB_BEN_KILANI,
    AKRAM_NAILY,
    WAEL_AJANGUI,
    SOFIENE_JBARA,
    JASSER_GUIRAT,
    NIZAR_RYEHI,
    ANOUAR_AKROUTI,
    ABDESSALEM_MANI,
    HOUSSEM_BOULAARAS,
    SAIF_WERTANI,
    HASSAN_SELMI,
    MAHMOUD_KSAYAA,
    AHMED_DHOUIOUI
}
