pipeline {
    agent any
    tools {
        maven 'M2_HOME'
    }
    stages {

        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }

        stage('GIT') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Houssem-Ellouze/TransfertMarket.git'
                    // credentialsId: ''
            }
        }

        stage('MAVEN') {
            steps {
                sh "mvn -version"
            }
        }
    }
}
